/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.multi.factor.authentication.email.otp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MFAEmailOTP service. Represents a row in the &quot;MFAEmailOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.multi.factor.authentication.email.otp.model.impl.MFAEmailOTPModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.multi.factor.authentication.email.otp.model.impl.MFAEmailOTPImpl</code>.
 * </p>
 *
 * @author Arthur Chan
 * @see MFAEmailOTP
 * @generated
 */
@ProviderType
public interface MFAEmailOTPModel
	extends AuditedModel, BaseModel<MFAEmailOTP>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mfa email otp model instance should use the {@link MFAEmailOTP} interface instead.
	 */

	/**
	 * Returns the primary key of this mfa email otp.
	 *
	 * @return the primary key of this mfa email otp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mfa email otp.
	 *
	 * @param primaryKey the primary key of this mfa email otp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this mfa email otp.
	 *
	 * @return the mvcc version of this mfa email otp
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this mfa email otp.
	 *
	 * @param mvccVersion the mvcc version of this mfa email otp
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the email otp ID of this mfa email otp.
	 *
	 * @return the email otp ID of this mfa email otp
	 */
	public long getEmailOTPId();

	/**
	 * Sets the email otp ID of this mfa email otp.
	 *
	 * @param emailOTPId the email otp ID of this mfa email otp
	 */
	public void setEmailOTPId(long emailOTPId);

	/**
	 * Returns the company ID of this mfa email otp.
	 *
	 * @return the company ID of this mfa email otp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mfa email otp.
	 *
	 * @param companyId the company ID of this mfa email otp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this mfa email otp.
	 *
	 * @return the user ID of this mfa email otp
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this mfa email otp.
	 *
	 * @param userId the user ID of this mfa email otp
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mfa email otp.
	 *
	 * @return the user uuid of this mfa email otp
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this mfa email otp.
	 *
	 * @param userUuid the user uuid of this mfa email otp
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this mfa email otp.
	 *
	 * @return the user name of this mfa email otp
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this mfa email otp.
	 *
	 * @param userName the user name of this mfa email otp
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this mfa email otp.
	 *
	 * @return the create date of this mfa email otp
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this mfa email otp.
	 *
	 * @param createDate the create date of this mfa email otp
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mfa email otp.
	 *
	 * @return the modified date of this mfa email otp
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mfa email otp.
	 *
	 * @param modifiedDate the modified date of this mfa email otp
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the failed attempts of this mfa email otp.
	 *
	 * @return the failed attempts of this mfa email otp
	 */
	public int getFailedAttempts();

	/**
	 * Sets the failed attempts of this mfa email otp.
	 *
	 * @param failedAttempts the failed attempts of this mfa email otp
	 */
	public void setFailedAttempts(int failedAttempts);

	/**
	 * Returns the last fail date of this mfa email otp.
	 *
	 * @return the last fail date of this mfa email otp
	 */
	public Date getLastFailDate();

	/**
	 * Sets the last fail date of this mfa email otp.
	 *
	 * @param lastFailDate the last fail date of this mfa email otp
	 */
	public void setLastFailDate(Date lastFailDate);

	/**
	 * Returns the last fail ip of this mfa email otp.
	 *
	 * @return the last fail ip of this mfa email otp
	 */
	@AutoEscape
	public String getLastFailIP();

	/**
	 * Sets the last fail ip of this mfa email otp.
	 *
	 * @param lastFailIP the last fail ip of this mfa email otp
	 */
	public void setLastFailIP(String lastFailIP);

	/**
	 * Returns the last success date of this mfa email otp.
	 *
	 * @return the last success date of this mfa email otp
	 */
	public Date getLastSuccessDate();

	/**
	 * Sets the last success date of this mfa email otp.
	 *
	 * @param lastSuccessDate the last success date of this mfa email otp
	 */
	public void setLastSuccessDate(Date lastSuccessDate);

	/**
	 * Returns the last success ip of this mfa email otp.
	 *
	 * @return the last success ip of this mfa email otp
	 */
	@AutoEscape
	public String getLastSuccessIP();

	/**
	 * Sets the last success ip of this mfa email otp.
	 *
	 * @param lastSuccessIP the last success ip of this mfa email otp
	 */
	public void setLastSuccessIP(String lastSuccessIP);

}