/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.multi.factor.authentication.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.service.persistence.impl.UserInputString;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MFATestEntry service. Represents a row in the &quot;MFATestEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.multi.factor.authentication.test.model.impl.MFATestEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.multi.factor.authentication.test.model.impl.MFATestEntryImpl</code>.
 * </p>
 *
 * @author Arthur Chan
 * @see MFATestEntry
 * @generated
 */
@ProviderType
public interface MFATestEntryModel extends BaseModel<MFATestEntry>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mfa test entry model instance should use the {@link MFATestEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this mfa test entry.
	 *
	 * @return the primary key of this mfa test entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mfa test entry.
	 *
	 * @param primaryKey the primary key of this mfa test entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this mfa test entry.
	 *
	 * @return the mvcc version of this mfa test entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this mfa test entry.
	 *
	 * @param mvccVersion the mvcc version of this mfa test entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the mfa test entry ID of this mfa test entry.
	 *
	 * @return the mfa test entry ID of this mfa test entry
	 */
	public long getMfaTestEntryId();

	/**
	 * Sets the mfa test entry ID of this mfa test entry.
	 *
	 * @param mfaTestEntryId the mfa test entry ID of this mfa test entry
	 */
	public void setMfaTestEntryId(long mfaTestEntryId);

	/**
	 * Returns the test string of this mfa test entry.
	 *
	 * @return the test string of this mfa test entry
	 */
	@AutoEscape
	public String getTestString();

	/**
	 * Sets the test string of this mfa test entry.
	 *
	 * @param testString the test string of this mfa test entry
	 */
	public void setTestString(String testString);

	/**
	 * Returns the test user input string of this mfa test entry.
	 *
	 * @return the test user input string of this mfa test entry
	 */
	public UserInputString getTestUserInputString();

	/**
	 * Sets the test user input string of this mfa test entry.
	 *
	 * @param testUserInputString the test user input string of this mfa test entry
	 */
	public void setTestUserInputString(UserInputString testUserInputString);

}